
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddressProvider", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressProvider {


    /**
     * 
     * @param id
     * @return
     *     returns AddressEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddress", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "GetAddress")
    @ResponseWrapper(localName = "getAddressResponse", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "GetAddressResponse")
    @Action(input = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/getAddressRequest", output = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/getAddressResponse")
    public AddressEntity getAddress(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns AddressEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAddress", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "SaveAddress")
    @ResponseWrapper(localName = "saveAddressResponse", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "SaveAddressResponse")
    @Action(input = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/saveAddressRequest", output = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/saveAddressResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/saveAddress/Fault/ConcurrentFault")
    })
    public AddressEntity saveAddress(
        @WebParam(name = "entity", targetNamespace = "")
        AddressEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        AddressEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAddress", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "DeleteAddress")
    @ResponseWrapper(localName = "deleteAddressResponse", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "DeleteAddressResponse")
    @Action(input = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/deleteAddressRequest", output = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/deleteAddressResponse")
    public boolean deleteAddress(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<AddressEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAddress", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "SearchAddress")
    @ResponseWrapper(localName = "searchAddressResponse", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", className = "SearchAddressResponse")
    @Action(input = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/searchAddressRequest", output = "http://address.plugins.aidcloud.odinoxin.de/AddressProvider/searchAddressResponse")
    public List<AddressEntity> searchAddress(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

}
