
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddressProviderService", targetNamespace = "http://address.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/AddressProvider?wsdl")
public class AddressProviderService
    extends Service
{

    private final static URL ADDRESSPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDRESSPROVIDERSERVICE_EXCEPTION;
    private final static QName ADDRESSPROVIDERSERVICE_QNAME = new QName("http://address.plugins.aidcloud.odinoxin.de/", "AddressProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/AddressProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDRESSPROVIDERSERVICE_WSDL_LOCATION = url;
        ADDRESSPROVIDERSERVICE_EXCEPTION = e;
    }

    public AddressProviderService() {
        super(__getWsdlLocation(), ADDRESSPROVIDERSERVICE_QNAME);
    }

    public AddressProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDRESSPROVIDERSERVICE_QNAME, features);
    }

    public AddressProviderService(URL wsdlLocation) {
        super(wsdlLocation, ADDRESSPROVIDERSERVICE_QNAME);
    }

    public AddressProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDRESSPROVIDERSERVICE_QNAME, features);
    }

    public AddressProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressProvider
     */
    @WebEndpoint(name = "AddressProviderPort")
    public AddressProvider getAddressProviderPort() {
        return super.getPort(new QName("http://address.plugins.aidcloud.odinoxin.de/", "AddressProviderPort"), AddressProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressProvider
     */
    @WebEndpoint(name = "AddressProviderPort")
    public AddressProvider getAddressProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://address.plugins.aidcloud.odinoxin.de/", "AddressProviderPort"), AddressProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDRESSPROVIDERSERVICE_EXCEPTION!= null) {
            throw ADDRESSPROVIDERSERVICE_EXCEPTION;
        }
        return ADDRESSPROVIDERSERVICE_WSDL_LOCATION;
    }

}
