
package de.odinoxin.aidware.aidcloud.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConcurrentFault", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/")
public class ConcurrentFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConcurrentFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConcurrentFault_Exception(String message, ConcurrentFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConcurrentFault_Exception(String message, ConcurrentFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ConcurrentFault
     */
    public ConcurrentFault getFaultInfo() {
        return faultInfo;
    }

}
