
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactTypeProviderService", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/ContactTypeProvider?wsdl")
public class ContactTypeProviderService
    extends Service
{

    private final static URL CONTACTTYPEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTTYPEPROVIDERSERVICE_EXCEPTION;
    private final static QName CONTACTTYPEPROVIDERSERVICE_QNAME = new QName("http://type.contact.plugins.aidcloud.odinoxin.de/", "ContactTypeProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/ContactTypeProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTTYPEPROVIDERSERVICE_WSDL_LOCATION = url;
        CONTACTTYPEPROVIDERSERVICE_EXCEPTION = e;
    }

    public ContactTypeProviderService() {
        super(__getWsdlLocation(), CONTACTTYPEPROVIDERSERVICE_QNAME);
    }

    public ContactTypeProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTTYPEPROVIDERSERVICE_QNAME, features);
    }

    public ContactTypeProviderService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTTYPEPROVIDERSERVICE_QNAME);
    }

    public ContactTypeProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTTYPEPROVIDERSERVICE_QNAME, features);
    }

    public ContactTypeProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactTypeProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactTypeProvider
     */
    @WebEndpoint(name = "ContactTypeProviderPort")
    public ContactTypeProvider getContactTypeProviderPort() {
        return super.getPort(new QName("http://type.contact.plugins.aidcloud.odinoxin.de/", "ContactTypeProviderPort"), ContactTypeProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactTypeProvider
     */
    @WebEndpoint(name = "ContactTypeProviderPort")
    public ContactTypeProvider getContactTypeProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://type.contact.plugins.aidcloud.odinoxin.de/", "ContactTypeProviderPort"), ContactTypeProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTTYPEPROVIDERSERVICE_EXCEPTION!= null) {
            throw CONTACTTYPEPROVIDERSERVICE_EXCEPTION;
        }
        return CONTACTTYPEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
