
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactTypeProvider", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactTypeProvider {


    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns ContactTypeEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveContactType", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "SaveContactType")
    @ResponseWrapper(localName = "saveContactTypeResponse", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "SaveContactTypeResponse")
    @Action(input = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/saveContactTypeRequest", output = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/saveContactTypeResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/saveContactType/Fault/ConcurrentFault")
    })
    public ContactTypeEntity saveContactType(
        @WebParam(name = "entity", targetNamespace = "")
        ContactTypeEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        ContactTypeEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "generateDefaults", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaults")
    @ResponseWrapper(localName = "generateDefaultsResponse", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaultsResponse")
    @Action(input = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/generateDefaultsRequest", output = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/generateDefaultsResponse")
    public void generateDefaults();

    /**
     * 
     * @param id
     * @return
     *     returns ContactTypeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContactType", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "GetContactType")
    @ResponseWrapper(localName = "getContactTypeResponse", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "GetContactTypeResponse")
    @Action(input = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/getContactTypeRequest", output = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/getContactTypeResponse")
    public ContactTypeEntity getContactType(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteContactType", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "DeleteContactType")
    @ResponseWrapper(localName = "deleteContactTypeResponse", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "DeleteContactTypeResponse")
    @Action(input = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/deleteContactTypeRequest", output = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/deleteContactTypeResponse")
    public boolean deleteContactType(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<ContactTypeEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchContactType", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "SearchContactType")
    @ResponseWrapper(localName = "searchContactTypeResponse", targetNamespace = "http://type.contact.plugins.aidcloud.odinoxin.de/", className = "SearchContactTypeResponse")
    @Action(input = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/searchContactTypeRequest", output = "http://type.contact.plugins.aidcloud.odinoxin.de/ContactTypeProvider/searchContactTypeResponse")
    public List<ContactTypeEntity> searchContactType(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

}
