
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactInformationProvider", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactInformationProvider {


    /**
     * 
     * @param id
     * @return
     *     returns ContactInformationEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContactInformation", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "GetContactInformation")
    @ResponseWrapper(localName = "getContactInformationResponse", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "GetContactInformationResponse")
    @Action(input = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/getContactInformationRequest", output = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/getContactInformationResponse")
    public ContactInformationEntity getContactInformation(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteContactInformation", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "DeleteContactInformation")
    @ResponseWrapper(localName = "deleteContactInformationResponse", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "DeleteContactInformationResponse")
    @Action(input = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/deleteContactInformationRequest", output = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/deleteContactInformationResponse")
    public boolean deleteContactInformation(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<ContactInformationEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchContactInformation", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "SearchContactInformation")
    @ResponseWrapper(localName = "searchContactInformationResponse", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "SearchContactInformationResponse")
    @Action(input = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/searchContactInformationRequest", output = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/searchContactInformationResponse")
    public List<ContactInformationEntity> searchContactInformation(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns ContactInformationEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveContactInformation", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "SaveContactInformation")
    @ResponseWrapper(localName = "saveContactInformationResponse", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", className = "SaveContactInformationResponse")
    @Action(input = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/saveContactInformationRequest", output = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/saveContactInformationResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://information.contact.plugins.aidcloud.odinoxin.de/ContactInformationProvider/saveContactInformation/Fault/ConcurrentFault")
    })
    public ContactInformationEntity saveContactInformation(
        @WebParam(name = "entity", targetNamespace = "")
        ContactInformationEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        ContactInformationEntity original)
        throws ConcurrentFault_Exception
    ;

}
