
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactInformationProviderService", targetNamespace = "http://information.contact.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/ContactInformationProvider?wsdl")
public class ContactInformationProviderService
    extends Service
{

    private final static URL CONTACTINFORMATIONPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTINFORMATIONPROVIDERSERVICE_EXCEPTION;
    private final static QName CONTACTINFORMATIONPROVIDERSERVICE_QNAME = new QName("http://information.contact.plugins.aidcloud.odinoxin.de/", "ContactInformationProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/ContactInformationProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTINFORMATIONPROVIDERSERVICE_WSDL_LOCATION = url;
        CONTACTINFORMATIONPROVIDERSERVICE_EXCEPTION = e;
    }

    public ContactInformationProviderService() {
        super(__getWsdlLocation(), CONTACTINFORMATIONPROVIDERSERVICE_QNAME);
    }

    public ContactInformationProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTINFORMATIONPROVIDERSERVICE_QNAME, features);
    }

    public ContactInformationProviderService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTINFORMATIONPROVIDERSERVICE_QNAME);
    }

    public ContactInformationProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTINFORMATIONPROVIDERSERVICE_QNAME, features);
    }

    public ContactInformationProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactInformationProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactInformationProvider
     */
    @WebEndpoint(name = "ContactInformationProviderPort")
    public ContactInformationProvider getContactInformationProviderPort() {
        return super.getPort(new QName("http://information.contact.plugins.aidcloud.odinoxin.de/", "ContactInformationProviderPort"), ContactInformationProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactInformationProvider
     */
    @WebEndpoint(name = "ContactInformationProviderPort")
    public ContactInformationProvider getContactInformationProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://information.contact.plugins.aidcloud.odinoxin.de/", "ContactInformationProviderPort"), ContactInformationProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTINFORMATIONPROVIDERSERVICE_EXCEPTION!= null) {
            throw CONTACTINFORMATIONPROVIDERSERVICE_EXCEPTION;
        }
        return CONTACTINFORMATIONPROVIDERSERVICE_WSDL_LOCATION;
    }

}
