
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryProvider", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryProvider {


    /**
     * 
     * @param id
     * @return
     *     returns CountryEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountry", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "GetCountry")
    @ResponseWrapper(localName = "getCountryResponse", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "GetCountryResponse")
    @Action(input = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/getCountryRequest", output = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/getCountryResponse")
    public CountryEntity getCountry(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns CountryEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveCountry", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "SaveCountry")
    @ResponseWrapper(localName = "saveCountryResponse", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "SaveCountryResponse")
    @Action(input = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/saveCountryRequest", output = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/saveCountryResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/saveCountry/Fault/ConcurrentFault")
    })
    public CountryEntity saveCountry(
        @WebParam(name = "entity", targetNamespace = "")
        CountryEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        CountryEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCountry", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "DeleteCountry")
    @ResponseWrapper(localName = "deleteCountryResponse", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "DeleteCountryResponse")
    @Action(input = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/deleteCountryRequest", output = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/deleteCountryResponse")
    public boolean deleteCountry(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<CountryEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchCountry", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "SearchCountry")
    @ResponseWrapper(localName = "searchCountryResponse", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", className = "SearchCountryResponse")
    @Action(input = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/searchCountryRequest", output = "http://country.plugins.aidcloud.odinoxin.de/CountryProvider/searchCountryResponse")
    public List<CountryEntity> searchCountry(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

}
