
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryProviderService", targetNamespace = "http://country.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/CountryProvider?wsdl")
public class CountryProviderService
    extends Service
{

    private final static URL COUNTRYPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYPROVIDERSERVICE_EXCEPTION;
    private final static QName COUNTRYPROVIDERSERVICE_QNAME = new QName("http://country.plugins.aidcloud.odinoxin.de/", "CountryProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/CountryProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYPROVIDERSERVICE_WSDL_LOCATION = url;
        COUNTRYPROVIDERSERVICE_EXCEPTION = e;
    }

    public CountryProviderService() {
        super(__getWsdlLocation(), COUNTRYPROVIDERSERVICE_QNAME);
    }

    public CountryProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYPROVIDERSERVICE_QNAME, features);
    }

    public CountryProviderService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYPROVIDERSERVICE_QNAME);
    }

    public CountryProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYPROVIDERSERVICE_QNAME, features);
    }

    public CountryProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryProvider
     */
    @WebEndpoint(name = "CountryProviderPort")
    public CountryProvider getCountryProviderPort() {
        return super.getPort(new QName("http://country.plugins.aidcloud.odinoxin.de/", "CountryProviderPort"), CountryProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryProvider
     */
    @WebEndpoint(name = "CountryProviderPort")
    public CountryProvider getCountryProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://country.plugins.aidcloud.odinoxin.de/", "CountryProviderPort"), CountryProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYPROVIDERSERVICE_EXCEPTION!= null) {
            throw COUNTRYPROVIDERSERVICE_EXCEPTION;
        }
        return COUNTRYPROVIDERSERVICE_WSDL_LOCATION;
    }

}
