
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LanguageProviderService", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/LanguageProvider?wsdl")
public class LanguageProviderService
    extends Service
{

    private final static URL LANGUAGEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException LANGUAGEPROVIDERSERVICE_EXCEPTION;
    private final static QName LANGUAGEPROVIDERSERVICE_QNAME = new QName("http://language.plugins.aidcloud.odinoxin.de/", "LanguageProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/LanguageProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LANGUAGEPROVIDERSERVICE_WSDL_LOCATION = url;
        LANGUAGEPROVIDERSERVICE_EXCEPTION = e;
    }

    public LanguageProviderService() {
        super(__getWsdlLocation(), LANGUAGEPROVIDERSERVICE_QNAME);
    }

    public LanguageProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LANGUAGEPROVIDERSERVICE_QNAME, features);
    }

    public LanguageProviderService(URL wsdlLocation) {
        super(wsdlLocation, LANGUAGEPROVIDERSERVICE_QNAME);
    }

    public LanguageProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LANGUAGEPROVIDERSERVICE_QNAME, features);
    }

    public LanguageProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanguageProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LanguageProvider
     */
    @WebEndpoint(name = "LanguageProviderPort")
    public LanguageProvider getLanguageProviderPort() {
        return super.getPort(new QName("http://language.plugins.aidcloud.odinoxin.de/", "LanguageProviderPort"), LanguageProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageProvider
     */
    @WebEndpoint(name = "LanguageProviderPort")
    public LanguageProvider getLanguageProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://language.plugins.aidcloud.odinoxin.de/", "LanguageProviderPort"), LanguageProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LANGUAGEPROVIDERSERVICE_EXCEPTION!= null) {
            throw LANGUAGEPROVIDERSERVICE_EXCEPTION;
        }
        return LANGUAGEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
