
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LanguageProvider", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LanguageProvider {


    /**
     * 
     * @param id
     * @return
     *     returns LanguageEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLanguage", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "GetLanguage")
    @ResponseWrapper(localName = "getLanguageResponse", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "GetLanguageResponse")
    @Action(input = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/getLanguageRequest", output = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/getLanguageResponse")
    public LanguageEntity getLanguage(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "generateDefaults", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaults")
    @ResponseWrapper(localName = "generateDefaultsResponse", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaultsResponse")
    @Action(input = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/generateDefaultsRequest", output = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/generateDefaultsResponse")
    public void generateDefaults();

    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns LanguageEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveLanguage", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "SaveLanguage")
    @ResponseWrapper(localName = "saveLanguageResponse", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "SaveLanguageResponse")
    @Action(input = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/saveLanguageRequest", output = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/saveLanguageResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/saveLanguage/Fault/ConcurrentFault")
    })
    public LanguageEntity saveLanguage(
        @WebParam(name = "entity", targetNamespace = "")
        LanguageEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        LanguageEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLanguage", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "DeleteLanguage")
    @ResponseWrapper(localName = "deleteLanguageResponse", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "DeleteLanguageResponse")
    @Action(input = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/deleteLanguageRequest", output = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/deleteLanguageResponse")
    public boolean deleteLanguage(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<LanguageEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchLanguage", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "SearchLanguage")
    @ResponseWrapper(localName = "searchLanguageResponse", targetNamespace = "http://language.plugins.aidcloud.odinoxin.de/", className = "SearchLanguageResponse")
    @Action(input = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/searchLanguageRequest", output = "http://language.plugins.aidcloud.odinoxin.de/LanguageProvider/searchLanguageResponse")
    public List<LanguageEntity> searchLanguage(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

}
