
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Login", targetNamespace = "http://aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Login {


    /**
     * 
     * @param id
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSession", targetNamespace = "http://aidcloud.odinoxin.de/", className = "GetSession")
    @ResponseWrapper(localName = "getSessionResponse", targetNamespace = "http://aidcloud.odinoxin.de/", className = "GetSessionResponse")
    @Action(input = "http://aidcloud.odinoxin.de/Login/getSessionRequest", output = "http://aidcloud.odinoxin.de/Login/getSessionResponse")
    public String getSession(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd);

    /**
     * 
     * @param id
     * @param pwd
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkLogin", targetNamespace = "http://aidcloud.odinoxin.de/", className = "CheckLogin")
    @ResponseWrapper(localName = "checkLoginResponse", targetNamespace = "http://aidcloud.odinoxin.de/", className = "CheckLoginResponse")
    @Action(input = "http://aidcloud.odinoxin.de/Login/checkLoginRequest", output = "http://aidcloud.odinoxin.de/Login/checkLoginResponse")
    public boolean checkLogin(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd);

    /**
     * 
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<PersonEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchLogin", targetNamespace = "http://aidcloud.odinoxin.de/", className = "SearchLogin")
    @ResponseWrapper(localName = "searchLoginResponse", targetNamespace = "http://aidcloud.odinoxin.de/", className = "SearchLoginResponse")
    @Action(input = "http://aidcloud.odinoxin.de/Login/searchLoginRequest", output = "http://aidcloud.odinoxin.de/Login/searchLoginResponse")
    public List<PersonEntity> searchLogin(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max);

}
