
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NutritionTypeProviderService", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/NutritionTypeProvider?wsdl")
public class NutritionTypeProviderService
    extends Service
{

    private final static URL NUTRITIONTYPEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException NUTRITIONTYPEPROVIDERSERVICE_EXCEPTION;
    private final static QName NUTRITIONTYPEPROVIDERSERVICE_QNAME = new QName("http://nutritiontype.plugins.aidcloud.odinoxin.de/", "NutritionTypeProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/NutritionTypeProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NUTRITIONTYPEPROVIDERSERVICE_WSDL_LOCATION = url;
        NUTRITIONTYPEPROVIDERSERVICE_EXCEPTION = e;
    }

    public NutritionTypeProviderService() {
        super(__getWsdlLocation(), NUTRITIONTYPEPROVIDERSERVICE_QNAME);
    }

    public NutritionTypeProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NUTRITIONTYPEPROVIDERSERVICE_QNAME, features);
    }

    public NutritionTypeProviderService(URL wsdlLocation) {
        super(wsdlLocation, NUTRITIONTYPEPROVIDERSERVICE_QNAME);
    }

    public NutritionTypeProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NUTRITIONTYPEPROVIDERSERVICE_QNAME, features);
    }

    public NutritionTypeProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NutritionTypeProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NutritionTypeProvider
     */
    @WebEndpoint(name = "NutritionTypeProviderPort")
    public NutritionTypeProvider getNutritionTypeProviderPort() {
        return super.getPort(new QName("http://nutritiontype.plugins.aidcloud.odinoxin.de/", "NutritionTypeProviderPort"), NutritionTypeProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NutritionTypeProvider
     */
    @WebEndpoint(name = "NutritionTypeProviderPort")
    public NutritionTypeProvider getNutritionTypeProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nutritiontype.plugins.aidcloud.odinoxin.de/", "NutritionTypeProviderPort"), NutritionTypeProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NUTRITIONTYPEPROVIDERSERVICE_EXCEPTION!= null) {
            throw NUTRITIONTYPEPROVIDERSERVICE_EXCEPTION;
        }
        return NUTRITIONTYPEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
