
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NutritionTypeProvider", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NutritionTypeProvider {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "generateDefaults", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaults")
    @ResponseWrapper(localName = "generateDefaultsResponse", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaultsResponse")
    @Action(input = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/generateDefaultsRequest", output = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/generateDefaultsResponse")
    public void generateDefaults();

    /**
     * 
     * @param id
     * @return
     *     returns NutritionTypeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNutritionType", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "GetNutritionType")
    @ResponseWrapper(localName = "getNutritionTypeResponse", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "GetNutritionTypeResponse")
    @Action(input = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/getNutritionTypeRequest", output = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/getNutritionTypeResponse")
    public NutritionTypeEntity getNutritionType(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<NutritionTypeEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchNutritionType", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "SearchNutritionType")
    @ResponseWrapper(localName = "searchNutritionTypeResponse", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "SearchNutritionTypeResponse")
    @Action(input = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/searchNutritionTypeRequest", output = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/searchNutritionTypeResponse")
    public List<NutritionTypeEntity> searchNutritionType(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns NutritionTypeEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveNutritionType", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "SaveNutritionType")
    @ResponseWrapper(localName = "saveNutritionTypeResponse", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "SaveNutritionTypeResponse")
    @Action(input = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/saveNutritionTypeRequest", output = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/saveNutritionTypeResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/saveNutritionType/Fault/ConcurrentFault")
    })
    public NutritionTypeEntity saveNutritionType(
        @WebParam(name = "entity", targetNamespace = "")
        NutritionTypeEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        NutritionTypeEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteNutritionType", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "DeleteNutritionType")
    @ResponseWrapper(localName = "deleteNutritionTypeResponse", targetNamespace = "http://nutritiontype.plugins.aidcloud.odinoxin.de/", className = "DeleteNutritionTypeResponse")
    @Action(input = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/deleteNutritionTypeRequest", output = "http://nutritiontype.plugins.aidcloud.odinoxin.de/NutritionTypeProvider/deleteNutritionTypeResponse")
    public boolean deleteNutritionType(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
