
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonProvider", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonProvider {


    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns PersonEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePerson", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "SavePerson")
    @ResponseWrapper(localName = "savePersonResponse", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "SavePersonResponse")
    @Action(input = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/savePersonRequest", output = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/savePersonResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/savePerson/Fault/ConcurrentFault")
    })
    public PersonEntity savePerson(
        @WebParam(name = "entity", targetNamespace = "")
        PersonEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        PersonEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param currentPwd
     * @param newPwd
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePwd", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "ChangePwd")
    @ResponseWrapper(localName = "changePwdResponse", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "ChangePwdResponse")
    @Action(input = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/changePwdRequest", output = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/changePwdResponse")
    public boolean changePwd(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "currentPwd", targetNamespace = "")
        String currentPwd,
        @WebParam(name = "newPwd", targetNamespace = "")
        String newPwd);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<PersonEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPerson", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "SearchPerson")
    @ResponseWrapper(localName = "searchPersonResponse", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "SearchPersonResponse")
    @Action(input = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/searchPersonRequest", output = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/searchPersonResponse")
    public List<PersonEntity> searchPerson(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

    /**
     * 
     * @param id
     * @return
     *     returns PersonEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "GetPersonResponse")
    @Action(input = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/getPersonRequest", output = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/getPersonResponse")
    public PersonEntity getPerson(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "DeletePersonResponse")
    @Action(input = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/deletePersonRequest", output = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/deletePersonResponse")
    public boolean deletePerson(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "generateDefaults", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaults")
    @ResponseWrapper(localName = "generateDefaultsResponse", targetNamespace = "http://person.plugins.aidcloud.odinoxin.de/", className = "GenerateDefaultsResponse")
    @Action(input = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/generateDefaultsRequest", output = "http://person.plugins.aidcloud.odinoxin.de/PersonProvider/generateDefaultsResponse")
    public void generateDefaults();

}
