
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RotaShiftProvider", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RotaShiftProvider {


    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns RotaShiftEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveRotaShift", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "SaveRotaShift")
    @ResponseWrapper(localName = "saveRotaShiftResponse", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "SaveRotaShiftResponse")
    @Action(input = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/saveRotaShiftRequest", output = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/saveRotaShiftResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/saveRotaShift/Fault/ConcurrentFault")
    })
    public RotaShiftEntity saveRotaShift(
        @WebParam(name = "entity", targetNamespace = "")
        RotaShiftEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        RotaShiftEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRotaShift", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "DeleteRotaShift")
    @ResponseWrapper(localName = "deleteRotaShiftResponse", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "DeleteRotaShiftResponse")
    @Action(input = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/deleteRotaShiftRequest", output = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/deleteRotaShiftResponse")
    public boolean deleteRotaShift(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<RotaShiftEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchRotaShift", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "SearchRotaShift")
    @ResponseWrapper(localName = "searchRotaShiftResponse", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "SearchRotaShiftResponse")
    @Action(input = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/searchRotaShiftRequest", output = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/searchRotaShiftResponse")
    public List<RotaShiftEntity> searchRotaShift(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

    /**
     * 
     * @param id
     * @return
     *     returns RotaShiftEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRotaShift", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "GetRotaShift")
    @ResponseWrapper(localName = "getRotaShiftResponse", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", className = "GetRotaShiftResponse")
    @Action(input = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/getRotaShiftRequest", output = "http://shift.rota.plugins.aidcloud.odinoxin.de/RotaShiftProvider/getRotaShiftResponse")
    public RotaShiftEntity getRotaShift(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
