
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RotaShiftProviderService", targetNamespace = "http://shift.rota.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/RotaShiftProvider?wsdl")
public class RotaShiftProviderService
    extends Service
{

    private final static URL ROTASHIFTPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROTASHIFTPROVIDERSERVICE_EXCEPTION;
    private final static QName ROTASHIFTPROVIDERSERVICE_QNAME = new QName("http://shift.rota.plugins.aidcloud.odinoxin.de/", "RotaShiftProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/RotaShiftProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROTASHIFTPROVIDERSERVICE_WSDL_LOCATION = url;
        ROTASHIFTPROVIDERSERVICE_EXCEPTION = e;
    }

    public RotaShiftProviderService() {
        super(__getWsdlLocation(), ROTASHIFTPROVIDERSERVICE_QNAME);
    }

    public RotaShiftProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROTASHIFTPROVIDERSERVICE_QNAME, features);
    }

    public RotaShiftProviderService(URL wsdlLocation) {
        super(wsdlLocation, ROTASHIFTPROVIDERSERVICE_QNAME);
    }

    public RotaShiftProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROTASHIFTPROVIDERSERVICE_QNAME, features);
    }

    public RotaShiftProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RotaShiftProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RotaShiftProvider
     */
    @WebEndpoint(name = "RotaShiftProviderPort")
    public RotaShiftProvider getRotaShiftProviderPort() {
        return super.getPort(new QName("http://shift.rota.plugins.aidcloud.odinoxin.de/", "RotaShiftProviderPort"), RotaShiftProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RotaShiftProvider
     */
    @WebEndpoint(name = "RotaShiftProviderPort")
    public RotaShiftProvider getRotaShiftProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://shift.rota.plugins.aidcloud.odinoxin.de/", "RotaShiftProviderPort"), RotaShiftProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROTASHIFTPROVIDERSERVICE_EXCEPTION!= null) {
            throw ROTASHIFTPROVIDERSERVICE_EXCEPTION;
        }
        return ROTASHIFTPROVIDERSERVICE_WSDL_LOCATION;
    }

}
