
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RotaCategoryProviderService", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/RotaCategoryProvider?wsdl")
public class RotaCategoryProviderService
    extends Service
{

    private final static URL ROTACATEGORYPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROTACATEGORYPROVIDERSERVICE_EXCEPTION;
    private final static QName ROTACATEGORYPROVIDERSERVICE_QNAME = new QName("http://category.rota.plugins.aidcloud.odinoxin.de/", "RotaCategoryProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/RotaCategoryProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROTACATEGORYPROVIDERSERVICE_WSDL_LOCATION = url;
        ROTACATEGORYPROVIDERSERVICE_EXCEPTION = e;
    }

    public RotaCategoryProviderService() {
        super(__getWsdlLocation(), ROTACATEGORYPROVIDERSERVICE_QNAME);
    }

    public RotaCategoryProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROTACATEGORYPROVIDERSERVICE_QNAME, features);
    }

    public RotaCategoryProviderService(URL wsdlLocation) {
        super(wsdlLocation, ROTACATEGORYPROVIDERSERVICE_QNAME);
    }

    public RotaCategoryProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROTACATEGORYPROVIDERSERVICE_QNAME, features);
    }

    public RotaCategoryProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RotaCategoryProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RotaCategoryProvider
     */
    @WebEndpoint(name = "RotaCategoryProviderPort")
    public RotaCategoryProvider getRotaCategoryProviderPort() {
        return super.getPort(new QName("http://category.rota.plugins.aidcloud.odinoxin.de/", "RotaCategoryProviderPort"), RotaCategoryProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RotaCategoryProvider
     */
    @WebEndpoint(name = "RotaCategoryProviderPort")
    public RotaCategoryProvider getRotaCategoryProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://category.rota.plugins.aidcloud.odinoxin.de/", "RotaCategoryProviderPort"), RotaCategoryProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROTACATEGORYPROVIDERSERVICE_EXCEPTION!= null) {
            throw ROTACATEGORYPROVIDERSERVICE_EXCEPTION;
        }
        return ROTACATEGORYPROVIDERSERVICE_WSDL_LOCATION;
    }

}
