
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RotaProviderService", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/RotaProvider?wsdl")
public class RotaProviderService
    extends Service
{

    private final static URL ROTAPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROTAPROVIDERSERVICE_EXCEPTION;
    private final static QName ROTAPROVIDERSERVICE_QNAME = new QName("http://rota.plugins.aidcloud.odinoxin.de/", "RotaProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/RotaProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROTAPROVIDERSERVICE_WSDL_LOCATION = url;
        ROTAPROVIDERSERVICE_EXCEPTION = e;
    }

    public RotaProviderService() {
        super(__getWsdlLocation(), ROTAPROVIDERSERVICE_QNAME);
    }

    public RotaProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROTAPROVIDERSERVICE_QNAME, features);
    }

    public RotaProviderService(URL wsdlLocation) {
        super(wsdlLocation, ROTAPROVIDERSERVICE_QNAME);
    }

    public RotaProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROTAPROVIDERSERVICE_QNAME, features);
    }

    public RotaProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RotaProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RotaProvider
     */
    @WebEndpoint(name = "RotaProviderPort")
    public RotaProvider getRotaProviderPort() {
        return super.getPort(new QName("http://rota.plugins.aidcloud.odinoxin.de/", "RotaProviderPort"), RotaProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RotaProvider
     */
    @WebEndpoint(name = "RotaProviderPort")
    public RotaProvider getRotaProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rota.plugins.aidcloud.odinoxin.de/", "RotaProviderPort"), RotaProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROTAPROVIDERSERVICE_EXCEPTION!= null) {
            throw ROTAPROVIDERSERVICE_EXCEPTION;
        }
        return ROTAPROVIDERSERVICE_WSDL_LOCATION;
    }

}
