
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RotaCategoryProvider", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RotaCategoryProvider {


    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns RotaCategoryEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveRotaCategory", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "SaveRotaCategory")
    @ResponseWrapper(localName = "saveRotaCategoryResponse", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "SaveRotaCategoryResponse")
    @Action(input = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/saveRotaCategoryRequest", output = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/saveRotaCategoryResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/saveRotaCategory/Fault/ConcurrentFault")
    })
    public RotaCategoryEntity saveRotaCategory(
        @WebParam(name = "entity", targetNamespace = "")
        RotaCategoryEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        RotaCategoryEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns RotaCategoryEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRotaCategory", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "GetRotaCategory")
    @ResponseWrapper(localName = "getRotaCategoryResponse", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "GetRotaCategoryResponse")
    @Action(input = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/getRotaCategoryRequest", output = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/getRotaCategoryResponse")
    public RotaCategoryEntity getRotaCategory(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRotaCategory", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "DeleteRotaCategory")
    @ResponseWrapper(localName = "deleteRotaCategoryResponse", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "DeleteRotaCategoryResponse")
    @Action(input = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/deleteRotaCategoryRequest", output = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/deleteRotaCategoryResponse")
    public boolean deleteRotaCategory(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<RotaCategoryEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchRotaCategory", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "SearchRotaCategory")
    @ResponseWrapper(localName = "searchRotaCategoryResponse", targetNamespace = "http://category.rota.plugins.aidcloud.odinoxin.de/", className = "SearchRotaCategoryResponse")
    @Action(input = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/searchRotaCategoryRequest", output = "http://category.rota.plugins.aidcloud.odinoxin.de/RotaCategoryProvider/searchRotaCategoryResponse")
    public List<RotaCategoryEntity> searchRotaCategory(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

}
