
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimestampInterpretationProviderService", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/TimestampInterpretationProvider?wsdl")
public class TimestampInterpretationProviderService
    extends Service
{

    private final static URL TIMESTAMPINTERPRETATIONPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESTAMPINTERPRETATIONPROVIDERSERVICE_EXCEPTION;
    private final static QName TIMESTAMPINTERPRETATIONPROVIDERSERVICE_QNAME = new QName("http://rota.plugins.aidcloud.odinoxin.de/", "TimestampInterpretationProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/TimestampInterpretationProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESTAMPINTERPRETATIONPROVIDERSERVICE_WSDL_LOCATION = url;
        TIMESTAMPINTERPRETATIONPROVIDERSERVICE_EXCEPTION = e;
    }

    public TimestampInterpretationProviderService() {
        super(__getWsdlLocation(), TIMESTAMPINTERPRETATIONPROVIDERSERVICE_QNAME);
    }

    public TimestampInterpretationProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMESTAMPINTERPRETATIONPROVIDERSERVICE_QNAME, features);
    }

    public TimestampInterpretationProviderService(URL wsdlLocation) {
        super(wsdlLocation, TIMESTAMPINTERPRETATIONPROVIDERSERVICE_QNAME);
    }

    public TimestampInterpretationProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMESTAMPINTERPRETATIONPROVIDERSERVICE_QNAME, features);
    }

    public TimestampInterpretationProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimestampInterpretationProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimestampInterpretationProvider
     */
    @WebEndpoint(name = "TimestampInterpretationProviderPort")
    public TimestampInterpretationProvider getTimestampInterpretationProviderPort() {
        return super.getPort(new QName("http://rota.plugins.aidcloud.odinoxin.de/", "TimestampInterpretationProviderPort"), TimestampInterpretationProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimestampInterpretationProvider
     */
    @WebEndpoint(name = "TimestampInterpretationProviderPort")
    public TimestampInterpretationProvider getTimestampInterpretationProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rota.plugins.aidcloud.odinoxin.de/", "TimestampInterpretationProviderPort"), TimestampInterpretationProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESTAMPINTERPRETATIONPROVIDERSERVICE_EXCEPTION!= null) {
            throw TIMESTAMPINTERPRETATIONPROVIDERSERVICE_EXCEPTION;
        }
        return TIMESTAMPINTERPRETATIONPROVIDERSERVICE_WSDL_LOCATION;
    }

}
