
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimestampInterpretationProvider", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimestampInterpretationProvider {


    /**
     * 
     * @param exceptIds
     * @param max
     * @param expr
     * @return
     *     returns java.util.List<TimestampInterpretationEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTimestampInterpretation", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "SearchTimestampInterpretation")
    @ResponseWrapper(localName = "searchTimestampInterpretationResponse", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "SearchTimestampInterpretationResponse")
    @Action(input = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/searchTimestampInterpretationRequest", output = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/searchTimestampInterpretationResponse")
    public List<TimestampInterpretationEntity> searchTimestampInterpretation(
        @WebParam(name = "expr", targetNamespace = "")
        List<String> expr,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "exceptIds", targetNamespace = "")
        List<Integer> exceptIds);

    /**
     * 
     * @param original
     * @param entity
     * @return
     *     returns TimestampInterpretationEntity
     * @throws ConcurrentFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveTimestampInterpretation", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "SaveTimestampInterpretation")
    @ResponseWrapper(localName = "saveTimestampInterpretationResponse", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "SaveTimestampInterpretationResponse")
    @Action(input = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/saveTimestampInterpretationRequest", output = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/saveTimestampInterpretationResponse", fault = {
        @FaultAction(className = ConcurrentFault_Exception.class, value = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/saveTimestampInterpretation/Fault/ConcurrentFault")
    })
    public TimestampInterpretationEntity saveTimestampInterpretation(
        @WebParam(name = "entity", targetNamespace = "")
        TimestampInterpretationEntity entity,
        @WebParam(name = "original", targetNamespace = "")
        TimestampInterpretationEntity original)
        throws ConcurrentFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns TimestampInterpretationEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimestampInterpretation", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "GetTimestampInterpretation")
    @ResponseWrapper(localName = "getTimestampInterpretationResponse", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "GetTimestampInterpretationResponse")
    @Action(input = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/getTimestampInterpretationRequest", output = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/getTimestampInterpretationResponse")
    public TimestampInterpretationEntity getTimestampInterpretation(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTimestampInterpretation", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "DeleteTimestampInterpretation")
    @ResponseWrapper(localName = "deleteTimestampInterpretationResponse", targetNamespace = "http://rota.plugins.aidcloud.odinoxin.de/", className = "DeleteTimestampInterpretationResponse")
    @Action(input = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/deleteTimestampInterpretationRequest", output = "http://rota.plugins.aidcloud.odinoxin.de/TimestampInterpretationProvider/deleteTimestampInterpretationResponse")
    public boolean deleteTimestampInterpretation(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
