
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrackedChangeProviderService", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/TrackedChangeProvider?wsdl")
public class TrackedChangeProviderService
    extends Service
{

    private final static URL TRACKEDCHANGEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACKEDCHANGEPROVIDERSERVICE_EXCEPTION;
    private final static QName TRACKEDCHANGEPROVIDERSERVICE_QNAME = new QName("http://plugins.aidcloud.odinoxin.de/", "TrackedChangeProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/TrackedChangeProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRACKEDCHANGEPROVIDERSERVICE_WSDL_LOCATION = url;
        TRACKEDCHANGEPROVIDERSERVICE_EXCEPTION = e;
    }

    public TrackedChangeProviderService() {
        super(__getWsdlLocation(), TRACKEDCHANGEPROVIDERSERVICE_QNAME);
    }

    public TrackedChangeProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRACKEDCHANGEPROVIDERSERVICE_QNAME, features);
    }

    public TrackedChangeProviderService(URL wsdlLocation) {
        super(wsdlLocation, TRACKEDCHANGEPROVIDERSERVICE_QNAME);
    }

    public TrackedChangeProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRACKEDCHANGEPROVIDERSERVICE_QNAME, features);
    }

    public TrackedChangeProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackedChangeProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrackedChangeProvider
     */
    @WebEndpoint(name = "TrackedChangeProviderPort")
    public TrackedChangeProvider getTrackedChangeProviderPort() {
        return super.getPort(new QName("http://plugins.aidcloud.odinoxin.de/", "TrackedChangeProviderPort"), TrackedChangeProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrackedChangeProvider
     */
    @WebEndpoint(name = "TrackedChangeProviderPort")
    public TrackedChangeProvider getTrackedChangeProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://plugins.aidcloud.odinoxin.de/", "TrackedChangeProviderPort"), TrackedChangeProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACKEDCHANGEPROVIDERSERVICE_EXCEPTION!= null) {
            throw TRACKEDCHANGEPROVIDERSERVICE_EXCEPTION;
        }
        return TRACKEDCHANGEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
