
package de.odinoxin.aidware.aidcloud.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrackedChangeProvider", targetNamespace = "http://plugins.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackedChangeProvider {


    /**
     * 
     * @param entityName
     * @param entityId
     * @return
     *     returns TrackedChangeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastChangeEntry", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", className = "GetLastChangeEntry")
    @ResponseWrapper(localName = "getLastChangeEntryResponse", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", className = "GetLastChangeEntryResponse")
    @Action(input = "http://plugins.aidcloud.odinoxin.de/TrackedChangeProvider/getLastChangeEntryRequest", output = "http://plugins.aidcloud.odinoxin.de/TrackedChangeProvider/getLastChangeEntryResponse")
    public TrackedChangeEntity getLastChangeEntry(
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        int entityId);

    /**
     * 
     * @param entityName
     * @param entityId
     * @param since
     * @return
     *     returns java.util.List<TrackedChangeEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityChanges", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", className = "GetEntityChanges")
    @ResponseWrapper(localName = "getEntityChangesResponse", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", className = "GetEntityChangesResponse")
    @Action(input = "http://plugins.aidcloud.odinoxin.de/TrackedChangeProvider/getEntityChangesRequest", output = "http://plugins.aidcloud.odinoxin.de/TrackedChangeProvider/getEntityChangesResponse")
    public List<TrackedChangeEntity> getEntityChanges(
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        int entityId,
        @WebParam(name = "since", targetNamespace = "")
        XMLGregorianCalendar since);

    /**
     * 
     * @param entityName
     * @param entityId
     * @return
     *     returns TrackedChangeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCreationEntry", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", className = "GetCreationEntry")
    @ResponseWrapper(localName = "getCreationEntryResponse", targetNamespace = "http://plugins.aidcloud.odinoxin.de/", className = "GetCreationEntryResponse")
    @Action(input = "http://plugins.aidcloud.odinoxin.de/TrackedChangeProvider/getCreationEntryRequest", output = "http://plugins.aidcloud.odinoxin.de/TrackedChangeProvider/getCreationEntryResponse")
    public TrackedChangeEntity getCreationEntry(
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        int entityId);

}
