
package de.odinoxin.aidware.aidcloud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TranslatorService", targetNamespace = "http://translation.aidcloud.odinoxin.de/", wsdlLocation = "http://SPUTNIK:15123/AidCloud/Translator?wsdl")
public class TranslatorService
    extends Service
{

    private final static URL TRANSLATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSLATORSERVICE_EXCEPTION;
    private final static QName TRANSLATORSERVICE_QNAME = new QName("http://translation.aidcloud.odinoxin.de/", "TranslatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SPUTNIK:15123/AidCloud/Translator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSLATORSERVICE_WSDL_LOCATION = url;
        TRANSLATORSERVICE_EXCEPTION = e;
    }

    public TranslatorService() {
        super(__getWsdlLocation(), TRANSLATORSERVICE_QNAME);
    }

    public TranslatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSLATORSERVICE_QNAME, features);
    }

    public TranslatorService(URL wsdlLocation) {
        super(wsdlLocation, TRANSLATORSERVICE_QNAME);
    }

    public TranslatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSLATORSERVICE_QNAME, features);
    }

    public TranslatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranslatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Translator
     */
    @WebEndpoint(name = "TranslatorPort")
    public Translator getTranslatorPort() {
        return super.getPort(new QName("http://translation.aidcloud.odinoxin.de/", "TranslatorPort"), Translator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Translator
     */
    @WebEndpoint(name = "TranslatorPort")
    public Translator getTranslatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://translation.aidcloud.odinoxin.de/", "TranslatorPort"), Translator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSLATORSERVICE_EXCEPTION!= null) {
            throw TRANSLATORSERVICE_EXCEPTION;
        }
        return TRANSLATORSERVICE_WSDL_LOCATION;
    }

}
