
package de.odinoxin.aidware.aidcloud.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Translator", targetNamespace = "http://translation.aidcloud.odinoxin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Translator {


    /**
     * 
     * @param lng
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTranslation", targetNamespace = "http://translation.aidcloud.odinoxin.de/", className = "GetTranslation")
    @ResponseWrapper(localName = "getTranslationResponse", targetNamespace = "http://translation.aidcloud.odinoxin.de/", className = "GetTranslationResponse")
    @Action(input = "http://translation.aidcloud.odinoxin.de/Translator/getTranslationRequest", output = "http://translation.aidcloud.odinoxin.de/Translator/getTranslationResponse")
    public String getTranslation(
        @WebParam(name = "text", targetNamespace = "")
        String text,
        @WebParam(name = "lng", targetNamespace = "")
        LanguageEntity lng);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "generateDefaults", targetNamespace = "http://translation.aidcloud.odinoxin.de/", className = "GenerateDefaults")
    @ResponseWrapper(localName = "generateDefaultsResponse", targetNamespace = "http://translation.aidcloud.odinoxin.de/", className = "GenerateDefaultsResponse")
    @Action(input = "http://translation.aidcloud.odinoxin.de/Translator/generateDefaultsRequest", output = "http://translation.aidcloud.odinoxin.de/Translator/generateDefaultsResponse")
    public void generateDefaults();

}
